# Numpy Mathematical Operations

In [1]:
import numpy as np
arr1=np.array([1,3,4,5,6,7,8,9,1])
arr2=np.array([2,1,3,4,5,6,7,8,14])
print(arr1)
print(arr2)
type(arr1)

[1 3 4 5 6 7 8 9 1]
[ 2  1  3  4  5  6  7  8 14]


numpy.ndarray

In [2]:
# add 2 arrays
np.add(arr1,arr2)

array([ 3,  4,  7,  9, 11, 13, 15, 17, 15])

In [3]:
#Subtract 2 arrays
np.subtract(arr1,arr2)

array([ -1,   2,   1,   1,   1,   1,   1,   1, -13])

In [4]:
#multipy 2 arrays
np.multiply(arr1,arr2)

array([ 2,  3, 12, 20, 30, 42, 56, 72, 14])

In [5]:
#divide 2 arrays
np.divide(arr1,arr2)

array([0.5       , 3.        , 1.33333333, 1.25      , 1.2       ,
       1.16666667, 1.14285714, 1.125     , 0.07142857])

In [6]:
arr1_new=arr1.reshape(3,3)
print(arr1_new)

[[1 3 4]
 [5 6 7]
 [8 9 1]]


In [7]:
#maximum of arr1 
np.max(arr1_new)

9

In [8]:
#index of maximum number
np.argmax(arr1_new)

7

In [9]:
#Row wise maximum number
np.max(arr1_new,axis=0)

array([8, 9, 7])

In [12]:
#column wise maximum number
np.max(arr1_new,axis=1)

array([4, 7, 9])

In [11]:
#minimum of arr1 
np.min(arr1_new)

1

In [13]:
#index of minimum number
np.argmin(arr1_new)

0

In [14]:
#Row wise minimum number
np.min(arr1_new,axis=0)

array([1, 3, 1])

In [15]:
#column wise minimum number
np.min(arr1_new,axis=1)

array([1, 5, 1])

In [19]:
#sum of all array elements
np.sum(arr1_new)

44

In [21]:
#sum of all array row wise
np.sum(arr1_new,axis=1)

array([ 8, 18, 18])

In [22]:
#column wise sum of elements
np.sum(arr1_new,axis=0)

array([14, 18, 12])

In [25]:
#mean of all array elements
np.mean(arr1_new)

4.888888888888889

In [26]:
#square root of all array elements
np.sqrt(arr1_new)

array([[1.        , 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 1.        ]])

In [27]:
#exponential of all array elements
np.exp(arr1_new)

array([[2.71828183e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.71828183e+00]])

In [28]:
#natural log of array elements
np.log(arr1_new)

array([[0.        , 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 0.        ]])

In [30]:
#log base to 10 of array elements
np.log10(arr1_new)

array([[0.        , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 0.        ]])