# Numpy Array Slicing

In [1]:
import numpy as np

In [2]:
mx=np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
#get element of 4th row and 5th coloumn
mx[4,5]

46

In [4]:
#print 9th row only
mx[9]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
#print 7th column only
mx[0:,7]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [6]:
#array slicing
mx[2:5,4:7]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [7]:
#all rows and particular columns interval
mx[:,4:9]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

In [8]:
#all columns and particular row data
mx[3:6,:]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])