# Numpy Array Conctination & Split

In [1]:
import numpy as np
mx=np.arange(1,31).reshape(3,10)
my=np.arange(31,61).reshape(3,10)
print(mx)
print(my)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [2]:
#concatinate 2 arrays column wise
np.concatenate((mx,my))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [3]:
#concatinate 2 arrays Row wise
np.concatenate((mx,my),axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 41, 42, 43, 44, 45, 46,
        47, 48, 49, 50],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60]])

In [4]:
#concatinate 2 arrays column wise
np.vstack((mx,my))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [5]:
#concatinate 2 arrays Row wise
np.hstack((mx,my))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 41, 42, 43, 44, 45, 46,
        47, 48, 49, 50],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60]])

In [6]:
#Split Array in n parts
#number of array division(n) should equal to number of rows
np.split(my,3)

[array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]),
 array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]),
 array([[51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])]

In [7]:
#Split Array in n parts
#number of array division(n) should equal to number of rows
np.split(my,10,axis=1)

[array([[31],
        [41],
        [51]]),
 array([[32],
        [42],
        [52]]),
 array([[33],
        [43],
        [53]]),
 array([[34],
        [44],
        [54]]),
 array([[35],
        [45],
        [55]]),
 array([[36],
        [46],
        [56]]),
 array([[37],
        [47],
        [57]]),
 array([[38],
        [48],
        [58]]),
 array([[39],
        [49],
        [59]]),
 array([[40],
        [50],
        [60]])]