# Some Basic Numpy Operations

In [1]:
import numpy as np 
a = np.array([1,2,3]) #create 1d aarray
print(a)

[1 2 3]


In [2]:
a_2d=np.array([[1,2,3,4],[5,6,7,8]]) #creating 2d array
print(a_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
type(a) #printing type of entity
type(a_2d)

numpy.ndarray

In [4]:
#print dimensions of array
a_2d.ndim

2

In [5]:
#print element count in array
a_2d.size

8

In [6]:
#print shape i.e. no of rows and columns in array
a_2d.shape

(2, 4)

In [7]:
#print array element datatype
a_2d.dtype

dtype('int32')

In [8]:
#1s Matrix 
mx_1s=np.ones((5,5),dtype=int)
fx_1s=np.ones((5,5),dtype=float)
print(mx_1s)
print(fx_1s)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#0s Matrix 
mx_1s=np.zeros((5,5),dtype=int)
fx_1s=np.zeros((5,5),dtype=float)
print(mx_1s)
print(fx_1s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#create empty set containing random values
emptyset=np.empty((3,5))
print(emptyset)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#create array from range 1 to 12
arr1=np.arange(1,13)
print(arr1)
#create array of even numbers from range 1 to 12
arr_even=np.arange(2,12,2)
print(arr_even)
#create array of odd numbers from range 1 to 12
arr_odd=np.arange(1,12,2)
print(arr_odd)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10]
[ 1  3  5  7  9 11]


In [12]:
#change dimensions of array from 1d ro 2d
arr1_new=arr1.reshape(2,6)
print(arr1_new)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
#change dimensions of array from 1d ro 3d
arr1_new3d=arr1.reshape(3,4)
print(arr1_new3d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
#convert multidimensional array to 1d array
arr_new1d=arr1_new3d.ravel()
arr_new1d_2=arr1_new3d.flatten()
print(arr_new1d)
print(arr_new1d_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
#do transpose of matrix
arr1_tanspose=arr1_new3d.transpose()
print(arr1_tanspose)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
