# Numpy Trignometric Operations

In [1]:
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
arr1 = np.array([90, 180, 270, 360])

In [2]:
#print values of sin 
x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [3]:
#print vslues of cos
y = np.cos(arr)
print(y)

[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]


In [4]:
#print vslues of tan
z = np.tan(arr)
print(z)

[1.63312394e+16 1.73205081e+00 1.00000000e+00 7.26542528e-01]


In [5]:
#convert from degree to radian
a = np.deg2rad(arr1)
print(a)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [6]:
#convert from radian to degree
b = np.rad2deg(arr)
print(b)

[90. 60. 45. 36.]


In [9]:
#convert given value to angle in radian
c = np.arcsin(1.0)
d = np.arccos(1.0)
e = np.arctan(1.0)
print(c)
print(d)
print(e)

1.5707963267948966
0.0
0.7853981633974483
